### ISSUE TITLE
Blueprint will not import.

### ISSUE THREAD

**Issue by thescottyshouse** [asucrews/ha-blueprints#4]
**Describe the bug**
The Blueprint Import fails with the following error.
"Invalid blueprint: Missing input definition for auto_off"

**To Reproduce**
1. Go to 'Import Blueprint, 
2. Paste following link https://raw.githubusercontent.com/asucrews/ha-blueprints/main/automations/witb_plus/witb_plus.yaml Click Preview...'
3. Click on 'Preview....'
4. See error 'Invalid blueprint: Missing input definition for auto_off'

**Expected behavior**
Expected to se a preview of the Blueprint code, and after verifying validity, click Imprt to import the Blueprint into HomeAssistant.

**Desktop (please complete the following information):**
 - OS: [Windows 11 client, HomeAssistant (HASOS VM on Windows 11 Desktop)]
 - Browser [ chrome]

**Additional context**
I am not a coder so will need the clever folks to fix the blueprint import. :-) I manually created the Blueprint YAML, Copied the witb_plus.yaml file to the Blueprints/ and edited it, copying an  existing Input section and renamed it to auto_off (content is probably horribly wrong) but the  Blueprint can now load, and Automation can be created. (Doubt it will run correctly with my hack job)

edited section that I added. (Copied from bypass_finished_action:)
    auto_off:
      name: Auto Off (Optional)
      description: >
        Specify the action to be taken after the bypass auto-off timer finishes counting down.  This determines whether the automation should turn off lights or other devices when the bypass timer expires.<br/>
        <br/>Options:<br/>
        - Turn Off: Automatically turns off lights or devices when the bypass timer expires.<br/>
        - Do Nothing: Leaves lights or devices unchanged after the bypass timer expires.<br/>
        <br/>Default value: Turn Off. Only change if you intend to use this field and this input is optional.<br/>
      default: turn_off
      selector:
        select:
          mode: dropdown
          options:
          - label: Turn Off
            value: turn_off
          - label: Do Nothing
            value: do_nothing
          custom_value: false
          multiple: false
          sort: false

**Comment by asucrews** [comment]
@thescottyshouse Thanks! this should be fix now. I need to create a dev yaml to better support future changes

**Comment by thescottyshouse** [comment]
My pleasure.

Brilliant blueprint. Thank you very much.

Regards
Duane Scott.
