### ISSUE TITLE
device name is being reported as Node 7 instead of the friendly name

### ISSUE THREAD

**Issue by inphinitizeit** [asucrews/ha-blueprints#6]
**Describe the bug**
I've setup the lock management automation.  
When locking or unlocking the door the value used for the notification is not the name of the lock "Front Door Lock" but rather Node 7. 
<img width="621" alt="image" src="https://github.com/asucrews/ha-blueprints/assets/105890204/6d9c1506-e690-41df-ab6d-492bb9bb8fec">

However, when looking at the attributes of the lock "Node 7" cannot be found:
<img width="921" alt="image" src="https://github.com/asucrews/ha-blueprints/assets/105890204/810d66f1-2189-4d6b-bff6-9e58b59adae1">
<img width="1354" alt="image" src="https://github.com/asucrews/ha-blueprints/assets/105890204/4844adc9-a398-4457-8c5c-280feb1bfac5">

**To Reproduce**
Setup lock blueprint with notifications.
1. Lock or unlock the lock.

**Expected behavior**
The assigned name should show up in the notification

** Actual Behavior **
Node 7 is shown as the name instead.

**Home Assistant Info**
Install Type: OS/Docker/VM/Other
Core: 2024.6.4
Supervisor: 2024.06.2
Operating System: 12.3
Frontend: 20240610.1

**Comment by asucrews** [comment]
so odd, but i look in to it...might just need to switch to `{{ states.lock.x.name }}`

**Comment by asucrews** [comment]
I can not reproduce this, but not saying it not happening.  your lock

**Comment by asucrews** [comment]
@inphinitizeit When you have time, could you please try this development version? I would like to see if it resolves the issues.

https://github.com/asucrews/ha-blueprints/blob/main/automations/lock_management/dev/lock_management_dev.yaml

**Comment by inphinitizeit** [comment]
I'll give that a try but mysteriously after factory resetting the lock and re-adding it, its now using the friendly name. I suspect there are some zwave issues with schlage be469 locks and that is causing some of this strangeness.

**Comment by asucrews** [comment]
Are you using ZWaveJS UI addon or ZWaveJS addon?

**Comment by inphinitizeit** [comment]
ZwaveJS UI

**Comment by asucrews** [comment]
Do your names match in ZWaveJS UI and HA device page?
